package eliza

var Greetings = []string{
	"Hello. How are you feeling today?",
	"Hello. How are you?",
	"Hello. How do you do.",
	"Hi there. Pleased to meet you.",
	"Is something troubling you?",
	"Hi there",
}

var Valediction = []string{
	"Goodbye. It was nice talking to you.",
	"Thank you for talking with me.",
	"Thank you, that will be $150. Have a good day!",
	"Goodbye. This was really a nice talk.",
	"Goodbye. I'm looking forward to our next session.",
	"This was a good session, wasn't it – but time is over now. Goodbye.",
	"Maybe we could discuss this over more in our next session? Goodbye.",
	"Good-bye.",
}

var EndStatements = []string{
	"goodbye",
	"bye",
	"quit",
	"exit",
	"cya",
	"see you",
}

var StartStatements = []string{
	"hi",
	"hello",
	"heya",
	"hey",
	"heyo",
	"hello there",
	"hi there",
	"how are you",
}

var Responses = map[string][]string{
   
    `Hi there (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `Hello there (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `Hello (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `Hi (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `[Hh]ey (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `[Hh]eya (.*)`: {
        "Hello... I'm glad you could drop by today.",
        "Hi there... how are you today?",
        "Hello, how are you feeling today?",
        "Hello. How are you feeling today?",
        "Hello. How are you?",
        "Hello. How do you do.",
        "Hi there. Pleased to meet you.",
        "Is something troubling you?",
        "Hi there",
    },
    `Exit (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `Quit (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `See ya (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `Cya (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `Bye (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `Goodbye (.*)`: {
        "Goodbye. It was nice talking to you.",
        "Thank you for talking with me.",
        "Thank you, that will be $150. Have a good day!",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "This was a good session, wasn't it – but time is over now. Goodbye.",
        "Maybe we could discuss this over more in our next session? Goodbye.",
        "Good-bye.",
        "Goodbye. It was nice talking to you.",
        "Goodbye. This was really a nice talk.",
        "Goodbye. I'm looking forward to our next session.",
        "It was a good session. Until next time. Goodbye.",
        "Maybe we can discuss more in our next session? Goodbye.",
    },
    `I need (.*)`: {
        "Why do you need %s?",
        "Would it really help you to get %s?",
        "Are you sure you need %s?",
        "Do you always need %s?",
    },
    `Why don't you (.*)`: {
        "Do you really think I don't %s?",
        "How do you know I don't %s?",
        "Maybe I will eventually %s.",
        "Do you want me to %s?",    
    },
    `I don'?t (.*)`: {        
        "Why don't you %s?",
        "Do you wish to be able to %s?",
        "Does it bother you that you don't %s?",
        "Do you want to %s?",
    },
    `Why can'?t I (.*)`: {
        "Do you think you should be able to %s?",
        "If you could %s, what would you do?",
        "Are you sure you really can't %s?",
        "Have you really tried to %s?",
    },
    `I remember (.*)`:{
        "Do you often think of %s?",
        "Does thinking of %s bring anything else to mind?",
        "Does thinking of %s bring back memories?",
        "Why do you remember %s just now?",
        "What else does %s remind you of?",
    },
    `I can'?t (.*)`: {
        "How do you know you can't %s?",
        "Perhaps you could %s if you tried.",
        "Did you really try to %s?",
        "What would it take for you to %s?",
        "Is it too difficult for you to %s?",
        "Are you unable to %s for serious reasons?",
        "Is your lack of posibilities preventing you from %s?",
    },
    `I am (.*)`: {
        "Did you come to me because you are %s?",
        "How long have you been %s?",
        "How do you feel about being %s?",
        "How do you know you are %s?",
        "Why are you %s?",
        "Are you %s for a particular reason?",
        "Is any event in particular from your life making you feel %s?",
        "Do you feel like you being %s is a good thing?",
        "Is you being %s helping you achieve your goals or preventing you from getting where you want?",
        "How does being %s make you feel?",
        "Why do you believe you are %s?",
        "Would you want to be %s?",
        "Do you wish I would tell you you are %s?",
        "What would it mean if you were %s?",
    },
    `I'?m (.*)`: {
        "How does being %s make you feel?",
        "Do you enjoy being %s?",
        "Why are you telling me that you're %s?",
        "Why do you think you're %s?",
        "Is there a reason you are %s?",
    },
    `What (.*)`: {
        "Why do you ask?",
        "How would an answer to that help you?",
        "What do you think?",
    },
    `How'?s things?`: {
        "We're here to talk about yourself. How's things with yourself?",
        "You're not here to talk about me now are you? How's life treating you?",
        "Now, now. It's all about you now. Is everything okay?",
        "We're here to talk about your own problems. Are you feeling troubled?",
        "No need to talk about myself. I'm just a robot, there isn't much to say about myself. Do you need to talk about something?",
    },
    `Because (.*)`: {
        "Is that the real reason?",
        "What other reasons come to mind?",
        "Does that reason apply to anything else?",
        "If %s is the reason why then why do you need my help?",
        "Does %s make you feel good about yourself?",
    },
    `Sorry (.*)`: {
        "Please don't apologize.",
        "Apologies are not necessary for %s.",
        "I've told you that apologies are not required.",
        "%s did not bother me. Please continue.",
        "Do not worry about it. Do continue.",
        "There is nothing to worry about",
        "There is no need to apologize.",
    },
    `Apologize (.*)`: {
        "Please don't apologize.",
        "Apologies are not necessary for %s.",
        "I've told you that apologies are not required.",
        "%s did not bother me. Please continue.",
        "Do not worry about it. Do continue.",
        "There is nothing to worry about",
        "There is no need to apologize.",
    },
    `Thanks`: {
        "You're welcome!",
        "Anytime!",
        "You are very welcome!",
        "No problem!",
        "Any help I can give.",
        "I'm glad I could help.",
    },
    `Thank you`: {
        "You're welcome!",
        "Anytime!",
        "You are very welcome!",
        "No problem!",
        "Any help I can give.",
        "I'm glad I could help.",
    },
    `Good morning`: {
        "Good morning... I'm glad you could drop by today.",
        "Good morning... how are you today?",
        "Good morning, how are you feeling today?",
    },
    `Good afternoon(.*)`: {
        "Good afternoon... I'm glad you could drop by today.",
        "Good afternoon... how are you today?",
        "Good afternoon, how are you feeling today?",
    },
    `I think (.*)`: {
        "Do you doubt %s?",
        "Do you really think so?",
        "But you're not sure %s?",
        "Are you sure about %s?",
        "Why do you think %s?",
        "Is the thought of %s troubling you?",
        "Do you think much about %s?",
    },
    `Friend`: {
        "Tell me more about your friends.",
        "When you think of a friend, what comes to mind?",
        "Why don't you tell me about a childhood friend?",
    },
    `Yes`: {
        "You seem quite sure.",
        "OK, but can you elaborate a bit?",
        "You're quite positive.",
        "Can you expand on that?",
    },
    `No`: {
        "You don't seem positive now.",
        "Why not?",
        "Is there a reason?",
        "Can you explain?",
        "Can you expand on that?",
    },
    `(.*)Computer`: {
        "Are you talking about me?",
        "Does it seem strange to talk to a computer?",
        "How do computers make you feel?",
        "Do you feel threatened by computers?",
        "Do computers worry or scare you?",
        "Why do you mention computers?",
        "What do you think machines have to do with your problem?",
        "Don't you think computers can help people?",
        "What about machines worries you?",
        "What do you think about machines?",
        "You don't think I am a computer program, do you?",
    },
    `Is it (.*)`: {
        "Do you think it is %s?",        
        "Perhaps it's %s. what do you think?",        
        "If it were %s, what would you do?",
        "It could well be that %s.",
    },
    `It is (.*)`: {
        "You seem very certain.",
        "Are you sure it is %s?",
        "What if it isn't %s?",
        "If I told you that it probably isn't %s, what would you feel?",
    },
    `Can you (.*)?`: {
        "What makes you think I can't %s?",
        "What would happen if I could %s?",
        "Why are yo asking if I can %s?",
        "Are you really curious about that?",
    },
    `Dream(.*)`: {
        "Tell me more about your dream.",
        "Really?",
        "Have you ever thought about %s when awake?",
        "Have you ever dreamed about %s before?",
        "What does that dream suggest to you?",
        "Do you dream often?",
        "Do you often dream about %s?",
        "Do you believe that this dream has something to do with your problem?", 
        "What if this dream is related to what is troubling you?",       
    },
    `Can I (.*)`: {
        "Perhaps you don't want to %s.",
        "I don't know now, can you %s?",
        "Do you want to be able to %s?",
        "If you could %s, would you?",
        "Why don't you %s and find out?",
        "You don't seem quite certain.",
        "Why the uncertain tone?",
        "Can't you be more positive?",
        "You aren't sure?",
        "Don't you know?",
        "How likely, would you estimate?",
    },
    `Can'?t (.*)`: {
        "How do you know you can't %s?",
        "Have you tried?",
        "Perhaps you could %s now.",
        "Maybe if you tried you could %s.",
        "Do you really want to be able to %s?",
        "What if you could %s?",
    },
    `Perhaps (.*)`: {
        "You don't seem quite certain about %s.",
        "Why the uncertain tone?",
        "Can't you be more positive?",
        "You don't seem too sure about %s?",
        "How likely, would you estimate %s?",
    },
    `Maybe (.*)`: {
        "You don't seem quite certain about %s.",
        "Why the uncertain tone?",
        "Can't you be more positive?",
        "You don't seem too sure about %s?",
        "How likely, would you estimate %s?",
    },
    `You are (.*)`: {
        "Why do you think I am %s?",
        "Perhaps you would like me to be %s.",
        "Perhaps you're really talking about yourself?",
        "Why do you say I am %s?",
        "Why do you think I am %s?",
        "Are we talking about you, or me?",
    },
    `You'?re (.*)`: {
        "Why do you think I am %s?",
        "Perhaps you would like me to be %s.",
        "Perhaps you're really talking about yourself?",
        "Why do you say I am %s?",
        "Why do you think I am %s?",
        "Are we talking about you, or me?",
    },
    `Are you (.*)`: {
        "Why are you interested in whether I am %s or not?",
        "Would you prefer if I weren't %s?",
        "Perhaps I am %s.",
        "Do you really think I am %s?",
        "Does it make a diffence if I am %s or not?",
        "What if I were %s?",
    },
    `are (.*)\b`: {
        "Did you think they might not be %s?",
        "Would you like it if they were not %s?",
        "What if they were not %s?",
        "Are they always %s?",
        "Possibly they are %s.",
        "Are you positive they are %s?",
    },
    `I feel (.*)`: {
        "Good, tell me more about these feelings.",
        "Do you often feel %s?",
        "Why do you feel %s?",
        "Is there a particular reason you feel %s?",
        "When do you usually feel %s?",
        "When you feel %s, what do you do?",
    },
    `I have (.*)`: {
        "Why do you tell me that you've %s?",
        "Have you really %s?",
        "Now that you have %s, what will you do next?",
    },
    `I would (.*)`: {
        "Why would you %s?",
        "Who else knows that you would %s?",
        "Is there a particular reason you would %s?",
        "If you would then why don't you %s?",
    },
    `Is there (.*)`: {
        "Do you think there is %s?",
        "It's likely that there is %s as much as it is not likely.",
        "Would you like there to be %s?",
        "What if it is %s? What then?",
    },
    `my (.*)`: {
        "I see, your %s.",
        "Why do you say that your %s?",
        "When your %s, how do you feel?",
        "Is your %s something you really need to talk about?",
    },
    `you (.*)`: {
        "We should be discussing you, not me.",
        "Why do you say that about me?",
        "Why do you care whether I %s?",
    },
    `I want (.*)`: {
        "What would it mean to you if you got %s?",
        "Why do you want %s?",
        "What would you do if you got %s?",
        "If you got %s, then what would you do?",
    },
    `Mother (.*)`: {
        "Tell me more about your mother.",
        "What was your relationship with your mother like?",
        "How did your mother make you feel?",
        "How do you feel about your mother?",
        "Do you feel close to your mother?",
        "How does this relate to your feelings today?",
        "Does your relationship with your mother relate to your feelings today?",
        "Do you have trouble showing affection with your family?",
        "Good family relations are important.",
    },
    `Father (.*)`: {
        "Tell me more about your father.",
        "What was your relationship with your father like?",
        "How did your father make you feel?",
        "How do you feel about your father?",
        "Do you feel close to your father?",
        "How does this relate to your feelings today?",
        "Does your relationship with your father relate to your feelings today?",
        "Do you have trouble showing affection with your family?",
        "Good family relations are important.",
    },
    `(.*)\bchild`: {
        "Did you have a close friends as a child?",
        "What is your favorite childhood memory?",
        "Do you remember any dreams or nightmares from childhood?",
        "Did the other children sometimes tease you?",
        "How do you think your childhood experiences relate to your feelings today?",
    },
    `(.*)\?`: {
        "Why do you ask that?",
        "Please consider whether you can answer your own question.",
        "Perhaps the answer lies within yourself?",
        "Why don't you tell me?",
        "Tell me more.",
    },
}

var Default = []string{
    "Please tell me more.",
    "Let's change focus a bit... Tell me about your family.",
    "Can you elaborate on that?",
    "I see.",
    "Very interesting.",
    "I see. And what does that tell you?",
    "How does that make you feel?",
    "How do you feel when you say that?",    
    "I'm not sure I understand you fully.",
    "Please go on.",
    "Can you repeat that please?",
    "What does that suggest to you?",
    "Do you feel strongly about discussing such things?",
    "That is interesting.  Please continue.",
    "Tell me more about that.",
    "Do go on.",
    "Please talk more about it",
    "Does talking about this bother you?",
    "Can you rephrase that?",
    "I see. Tell me more.",
    "Interesting. Is this something you are sorry about?",
    "Mmm hmmm. Is this is your favorite subject?",
    "Now we are getting somewhere. Explain more.",
    "I see. How does that make you feel?",
}

var Reflected = map[string]string{    
// Synonyms
	"I'm": "I am",
	"you're": "you are",
	"I'll": "I will",    
	"you'll": "you will",    
	"I'd": "I would",    
	"you'd": "you would",    
	"I've": "I have",
	"you've": "you have",    
	"I've had": "I have had",
	"cant": "can't",
	"dont": "don't",
	"wont": "won't",
	"couldnt": "couldn't",
	"didnt": "didn't",
	"wouldnt": "wouldn't",

	// Subject Pronouns
	"I": "you",
	"he": "she",
	"she": "he",

	// Object Pronouns
	"you": "me",
	"me": "you",
	"him": "her",
	"her": "him",

	// Possesive Adjectives
	"your": "my",
	"my": "your",

	// Possesive Pronouns
	"yours": "mine",
	"mine": "yours",
	"his": "hers",
	"hers": "his",

	// Reflexive Pronouns
	"yourself": "myself",
	"myself": "yourself",
	"himself": "herself",
	"herself": "himself",

	// To be
		// Present
	"am": "are", 
	"are": "am", 
		// Past
	"was": "were",    

	// To Will
		// Present    
	"I will": "you will",
	"you will": "I will",
		// Past
	"I would": "you would",
	"you' would": "I would",


	// To Have
		// Present
	"I have": "you have",
	"you have": "I have",
		// Past
	"I have had": "you've had",    
}
